apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-pod
          image: 180.150.207.73:5000/frontend@sha256:eafe8ad65f4a79370194dbf111db1f1e40043cd96faf04378fbfc2108a4cb98e
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: svc-app
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3001
      nodePort: 31000
