apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      nodeSelector: # nodeSelector 추가
        kubernetes.io/hostname: worker1r # 원하는 노드 이름 지정
      containers:
        - name: frontend-pod
          image: 119.197.27.55:5000/frontend@sha256:e5d1b81fdd7a64862f299e3b95d6df6f73dbe5d6d67365a73a8d770c3f537729
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: svc-app
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3001
      nodePort: 31000
